version: '3'
services:
  dev:
    image: keboolabot/go-utils-dev
    build: .
    ports:
      - "6060:6060"
    environment:
      # By default the `fsLocker` is used as .env variables are commented out
      - TEST_KBC_PROJECTS_LOCK_HOST
      - TEST_KBC_PROJECTS_LOCK_PASSWORD
    volumes:
      - ./:/code:z
      - cache:/tmp/cache
  redis:
    hostname: redis
    image: redis
    command: ["redis-server", "/etc/redis/redis.conf"]
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    environment:
      REDIS_PORT: 6379
volumes:
  cache:
