name: Build and test Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Check out source code
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          make install-tools

      - name: Lint and test
        run: |
          make lint
          make tests
